name: 'dashboard' #project name
version: '1.0.0'
config-version: 2

profile: 'dashboard'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  dashboard:
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: bikeleasing_consumer
