name: 'dashboard'
version: '1.0.0'
config-version: 2

profile: 'dashboard'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  dashboard:
    +materialized: table
    staging:
      +schema: bykeleasing_raw
    marts:
      +schema: bykeleasing_consumer
